# This workflow runs on commit to build a package which can be
# installed with Helios 1.6.  If the commit contains the text
# #patch then the patch level will be bumped.

name: CreateHelios16

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VEHICLE: M-2000C
  VEHICLECOMMONNAME: M-2000C
  MINHELIOSRELEASE: 1.6.5501.0000
  PROFILENAME: M-2000C Functional Test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date=$(date +'%d-%b-%Y')" >> $GITHUB_OUTPUT
          echo "actor=${GITHUB_ACTOR}" >> $GITHUB_OUTPUT
      - name: Bump version and push 
        id: bump_tag
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: HeliosVirtualCockpit
          DEFAULT_BUMP: 'patch'
          INITIAL_VERSION: '0.0.0'
      - name: Check outputs
        run: |
          #env
          echo ${{ env.VEHICLE }} - ${{ env.VEHICLECOMMONNAME }}
          echo "Commit SHA (short) - " ${{ steps.vars.outputs.sha_short }}
          echo "New Release - V " ${{ steps.bump_tag.outputs.tag }}
      - run: |
          mkdir -p output
          smallTag=$(echo ${{ steps.bump_tag.outputs.tag }} | cut -c1-5)
          echo 'Small Tag= '$smallTag
          sed -i -- 's#_ProfileVersionNumber#'"V ${{ steps.bump_tag.outputs.tag }}"'#g' '${{ env.VEHICLE }}/Helios/Profiles/M-2000C Functional Test.hpf'
          sed -i -- 's#_Vehicle#'"${{ env.VEHICLE }}"'#g' '${{ env.VEHICLE }}/Helios/Profiles/M-2000C Functional Test.hpf'
          sed -i -- 's#_CurrentDate#'"${{ steps.vars.outputs.date }}"'#g' '${{ env.VEHICLE }}/Helios/Profiles/M-2000C Functional Test.hpf'
          sed -i -- 's#_Repository#'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases"'#g' '${{ env.VEHICLE }}/Helios/Profiles/M-2000C Functional Test.hpf'
          mv '${{ env.VEHICLE }}/Helios/Profiles/M-2000C Functional Test.hpf' '${{ env.VEHICLE }}/Helios/Profiles/${{ env.PROFILENAME }} ${{ steps.bump_tag.outputs.actor }} ${{ steps.bump_tag.outputs.tag }}.hpf'
          echo Substituting info in the Profile16.json manifest
          sed -i -- 's/_MinimumReleaseLevel/${{ env.MINHELIOSRELEASE }}/g' Profile16.json
          sed -i -- 's/_ReleaseDate/'"$(date "+%d %B %Y")"'/g' Profile16.json
          sed -i -- 's/_ProfileVersionNumber/'"V${{ steps.bump_tag.outputs.tag }}"'/g' Profile16.json
          sed -i -- 's/_Vehicle/'"${{ env.VEHICLE }}"'/g' Profile16.json
          sed -i -- 's#_Repository#'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases"'#g' Profile16.json
          sed -i -- 's#_Author#'"${GITHUB_ACTOR}"'#g' Profile16.json
          #sed -i -- 's#_Author#Helios Virtual Cockpit#g' Profile16.json
          sed -i -- 's/_Vehicle/'"${{ env.VEHICLE }}"'/g' '${{ env.VEHICLECOMMONNAME }} Test - About this profile.md'
          sed -i -- 's#_ProfileVersionNumber#'"V ${{ steps.bump_tag.outputs.tag }}"'#g' '${{ env.VEHICLECOMMONNAME }} Test - About this profile.md'
          sed -i -- 's#_ProjectURL#'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"'#g' '${{ env.VEHICLECOMMONNAME }} Test - About this profile.md'
          sed -i -- 's#_Repository#'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases"'#g' '${{ env.VEHICLECOMMONNAME }} Test - About this profile.md'
          sed -i -- 's#_commit#'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"'#g' '${{ env.VEHICLECOMMONNAME }} Test - About this profile.md'
      - name: Package Files
        run: |
          mv ./${{ env.VEHICLE }}/Helios .
          zip -r output/${{ env.VEHICLE }}_Functional_Test_V${{ steps.bump_tag.outputs.tag }}.helios16 ./Profile16.json ./LICENSE ./*.md ./Helios/ -x ".git/*" ".github/*" "./Helios/Profiles/*.bak" "./Helios/Profiles/*.hply"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.VEHICLECOMMONNAME }} Test V${{ steps.bump_tag.outputs.tag }} helios16 profile package
          path: output/${{ env.VEHICLE }}_Functional_Test_V${{ steps.bump_tag.outputs.tag }}.helios16
          retention-days: 7